Altinn/altinn-cdn

schemas/json/layout/layout.schema.v1.json

Schema changes related to https://github.com/Altinn/altinn-studio/issues/5164

Added summary component definitions

---

altinn-apps/widgets/message.json
schemas/xsd/message.xsd

For documentation of message concept

Add message xsd

---

schemas/json/layout/layout.schema.v1.json

The original file have inconsistent use of indentation. First level is four spaces instead of two, which is used for the other levels. This produce a lot of noise in the diff, but it is possible to ignore whitespace.

Added LabelSettings to layout schema

---

fonts/altinn-din/altinn-din.css

https://github.com/Altinn/altinn-studio/issues/2834

add css file for Altinn-DIN font

---

schemas/json/layout/layout.schema.v1.json

https://github.com/Altinn/altinn-studio/issues/1515

Added grid prop to json-schema

---

schemas/json/layout/layout.schema.v1.json
schemas/json/layout/layoutSettings.schema.v1.json

- https://github.com/Altinn/altinn-studio/issues/5639
- https://github.com/Altinn/altinn-studio/issues/5640

Added new trigger + triggers on page level on json schemas

---

orgs/altinn-orgs.json

Add prod as environment for SKD

---

orgs/altinn-orgs.json

https://github.com/Altinn/altinn-studio/issues/6030

Added tt02 for NKR

---

schemas/json/layout/layout.schema.v1.json

Updated schema after changes in https://github.com/Altinn/altinn-studio/issues/5869

add group edit property to layout schema

---

schemas/json/prefill/prefill.schema.v1.json

https://github.com/Altinn/altinn-studio/issues/4827

Prefill: added userprofile.party + titles and descripions for fields

---

schemas/json/layout/layout.schema.v1.json

Schema validator missing image-type.

Added image in schema-validator

---

schemas/json/layout/layout.schema.v1.json

https://github.com/Altinn/altinn-studio/issues/7228

Add explanation of the keyword 'today'

---

schemas/json/layout/layout.schema.v1.json

- added json schema for instantiation button. docs: https://docs.altinn.studio/app/development/configuration/stateless/#instansiere-med-prefill
- also fixed some minor typos

added instantiation button to schema

---

schemas/json/layout/layout.schema.v1.json

https://github.com/Altinn/altinn-studio/issues/7164

added new prop to group to layout shcema

---

schemas/json/layout/layout.schema.v1.json

https://github.com/Altinn/altinn-studio/issues/7893

schema for secure options

---

schemas/json/layout/layout.schema.v1.json

@lorang92 
I'm not entirely sure what changes are needed for this. Is there anything else I have overlooked?

feat: add navigation bar

---

schemas/json/layout/layout.schema.v1.json

This feature was added in https://github.com/Altinn/altinn-studio/pull/8238

feat: add information about row/column layout for radio and checkboxes

---

schemas/json/layout/layout.schema.v1.json

Extracted from https://github.com/Altinn/altinn-cdn/pull/79 as I did not have write permissions on the fork.
Relates to https://github.com/Altinn/altinn-studio/pull/7545.

6479: Add fileuploadwithtag

---

schemas/json/layout/layout.schema.v1.json

Related to https://github.com/Altinn/altinn-studio/pull/8340

added option source to json schema

---

orgs/altinn-orgs.json

Give Gjenopptakelseskommisjonen and Helse Møre og Romsdal access to their production environments.
- https://github.com/Altinn/altinn-platform/issues/169
- https://github.com/Altinn/altinn-platform/issues/170

Give prod access to GK and HMRHF

---

schemas/json/layout/layout.schema.v1.json

This adds intelisense support for the PrintButton.
Adds "PrintButton" to the JSON-schema.
- Altinn/app-frontend-react#120

PrintButton in schema

---

schemas/json/layout/layout.schema.v1.json

Schema definitions for https://github.com/Altinn/app-frontend-react/pull/330

feat: group panel schema

---

schemas/json/layout/layout.schema.v1.json

Update form layout schema with new likert component
- Link to main PR: https://github.com/Altinn/app-frontend-react/pull/72

added likert component to layout schema

---

schemas/json/layout/layout.schema.v1.json

JSON-schema definition for multiple select component added in https://github.com/Altinn/app-frontend-react/pull/505

feat: added multiple select

---

schemas/json/layout/layout.schema.v1.json

- https://github.com/Altinn/app-frontend-react/issues/321
- https://github.com/Altinn/app-frontend-react/pull/498

add alertOnDelete to layout schema

---

.cdnignore
.github/scripts/release.sh
.github/workflows/deploy-to-staging-cdn.yaml

Workflow that copies files to staging CDN in azure. Some secrets needs to be added before this is meged

Workflow for deploy to staging cdn

---

.github/scripts/release.sh
.github/workflows/deploy-to-staging-cdn.yaml

Missing one \ in the release yaml file

Small bugfix for the release script

---

.github/workflows/deploy-to-production-cdn.yaml

Publish changes to production cdn

Add pipeline for production cdn

---

orgs/altinn-orgs.json

Make it possible for NKOM to perform deploy to their production environment.
- https://github.com/Altinn/altinn-support-private/issues/1991

Enable prod deploy for NKOM

---

orgs/altinn-orgs.json

Changes org title in english
- Internal request in Finanstilsynet.

Correction to KRT-orgname in eng. See logo for krt.

---

authorization/actionoptions.json
authorization/subjectoptions.json

Added options for designer policy designer

Copied options

---

studio/designer/news/news.nb.json

Added news to Studio about payment step is now available within process-editor.
- PR itself

added news for paymentstep

---

orgs/altinn-orgs.json

- This is related to creating a new organization, but we still missing a logo URL , Is this something we need to fix or someone can add it? 
https://github.com/Altinn/altinn-support-private/issues/3705

create new org rir

---

.github/workflows/deploy-to-staging-cdn.yaml

Disable on push trigger for staging pipeline

---

orgs/altinn-orgs.json

Add deploy rights production, FORS

---

config/environments.json

At21 has been removed so it should be reflected here as some apps consume this data

fix(environments): remove at21 from envs

---

schemas/json/README.md

The schemas are now maintained in app-frontend-react

Update README.md in json schema folder

---

orgs/altinn-orgs.json

Removed the tt02 environment for Indigo from altinn-orgs, as this environment has been deleted for this organization.
- PR itself

removed: remove tt02 env for Indigo

---

orgs/altinn-orgs.json

Add production as possible deploy target for IKT Agder.
- https://github.com/Altinn/altinn-support-private/issues/4336

Enable production deploy for ikta

---

orgs/altinn-orgs.json

Updated name and website after renaming from Kulturrådet to Kulturdirektoratet.
- PR itself

updated name and website after renaming from Kulturrådet to Kulturdirektoratet

---

orgs/altinn-orgs.json

- https://github.com/orgs/Altinn/projects/63/views/1?pane=issue&itemId=117675801&issue=Altinn%7Caltinn-support-private%7C4541

feat: Add tt02 as enviorment
